### PR TITLE
Travis setup

### LINKED ISSUE #8: Set up github actions to build and run tests
or Travis I guess?

### PR DESCRIPTION
**Pull request by omelkonian**
* closes #8

### CODE REVIEW

**Comment by UlfNorell** [comment]
With the changes to `make test` you must now install `agda2hs` globally in order to run the test. This seems like a bad change, since you might not want to do global installs when you are developing something. Is this really necessary for getting it running on travis?

**Comment by UlfNorell** [comment]
Also what do we need to do to see how this actually runs on travis?

**Comment by jmchapman** [comment]
Can we steal something from the Agda travis setup about avoiding global installation of a executable?

**Comment by omelkonian** [comment]
> With the changes to `make test` you must now install `agda2hs` globally in order to run the test. This seems like a bad change, since you might not want to do global installs when you are developing something. Is this really necessary for getting it running on travis?

You are right, we can avoid that by installing on a subfolder prior to testing, and then searching for the executable using `find`.
Let me update this real quick.

**Comment by omelkonian** [comment]
> Also what do we need to do to see how this actually runs on travis?

I have it running in my fork, so you can check all builds/executions on Travis.
Here is the latest one: https://travis-ci.com/github/omelkonian/agda2hs/builds/192734955 (which we will be able to access from a badge in the README).

**Comment by UlfNorell** [comment]
> You are right, we can avoid that by installing on a subfolder prior to testing, and then searching for the executable using find.

Does the `cabal exec` magic I put in there not work on travis?

**Comment by omelkonian** [comment]
> > You are right, we can avoid that by installing on a subfolder prior to testing, and then searching for the executable using find.
> 
> Does the `cabal exec` magic I put in there not work on travis?

Yep, something weird going on with caching.

**Comment by omelkonian** [comment]
New version without the need for a global executable: https://travis-ci.com/github/omelkonian/agda2hs/builds/193418668

**Review by UlfNorell — APPROVED** [review]

**Pull request merged**
